[package]
name = "polybar-forecast"
version = "0.1.0"
authors = ["Bertrand \"Kamek\" Bousquet <b.kamek@gmail.com>"]

[dependencies]
failure = "0.1.1"
serde = "1.0.27"
serde_qs = "0.3.0"
serde_json = "1.0.9"
serde_derive = "1.0.27"
reqwest = "0.8.2"
toml = "0.4.5"